export const countries = [
  { code: "+93", name: "Afganistán", flag: "🇦🇫" },
  { code: "+355", name: "Albania", flag: "🇦🇱" },
  { code: "+213", name: "Argelia", flag: "🇩🇿" },
  { code: "+376", name: "Andorra", flag: "🇦🇩" },
  { code: "+244", name: "Angola", flag: "🇦🇴" },
  { code: "+1", name: "Antigua y Barbuda", flag: "🇦🇬" },
  { code: "+54", name: "Argentina", flag: "🇦🇷" },
  { code: "+374", name: "Armenia", flag: "🇦🇲" },
  { code: "+61", name: "Australia", flag: "🇦🇺" },
  { code: "+43", name: "Austria", flag: "🇦🇹" },
  { code: "+994", name: "Azerbaiyán", flag: "🇦🇿" },
  { code: "+1", name: "Bahamas", flag: "🇧🇸" },
  { code: "+973", name: "Baréin", flag: "🇧🇭" },
  { code: "+880", name: "Bangladés", flag: "🇧🇩" },
  { code: "+1", name: "Barbados", flag: "🇧🇧" },
  { code: "+375", name: "Bielorrusia", flag: "🇧🇾" },
  { code: "+32", name: "Bélgica", flag: "🇧🇪" },
  { code: "+501", name: "Belice", flag: "🇧🇿" },
  { code: "+229", name: "Benín", flag: "🇧🇯" },
  { code: "+975", name: "Bután", flag: "🇧🇹" },
  { code: "+591", name: "Bolivia", flag: "🇧🇴" },
  { code: "+387", name: "Bosnia y Herzegovina", flag: "🇧🇦" },
  { code: "+267", name: "Botsuana", flag: "🇧🇼" },
  { code: "+55", name: "Brasil", flag: "🇧🇷" },
  { code: "+673", name: "Brunéi", flag: "🇧🇳" },
  { code: "+359", name: "Bulgaria", flag: "🇧🇬" },
  { code: "+226", name: "Burkina Faso", flag: "🇧🇫" },
  { code: "+257", name: "Burundi", flag: "🇧🇮" },
  { code: "+855", name: "Camboya", flag: "🇰🇭" },
  { code: "+237", name: "Camerún", flag: "🇨🇲" },
  { code: "+1", name: "Canadá", flag: "🇨🇦" },
  { code: "+238", name: "Cabo Verde", flag: "🇨🇻" },
  { code: "+236", name: "República Centroafricana", flag: "🇨🇫" },
  { code: "+235", name: "Chad", flag: "🇹🇩" },
  { code: "+56", name: "Chile", flag: "🇨🇱" },
  { code: "+86", name: "China", flag: "🇨🇳" },
  { code: "+57", name: "Colombia", flag: "🇨🇴" },
  { code: "+269", name: "Comoras", flag: "🇰🇲" },
  { code: "+242", name: "Congo", flag: "🇨🇬" },
  { code: "+243", name: "República Democrática del Congo", flag: "🇨🇩" },
  { code: "+682", name: "Islas Cook", flag: "🇨🇰" },
  { code: "+506", name: "Costa Rica", flag: "🇨🇷" },
  { code: "+225", name: "Costa de Marfil", flag: "🇨🇮" },
  { code: "+385", name: "Croacia", flag: "🇭🇷" },
  { code: "+53", name: "Cuba", flag: "🇨🇺" },
  { code: "+357", name: "Chipre", flag: "🇨🇾" },
  { code: "+420", name: "Chequia", flag: "🇨🇿" },
  { code: "+45", name: "Dinamarca", flag: "🇩🇰" },
  { code: "+253", name: "Yibuti", flag: "🇩🇯" },
  { code: "+1", name: "Dominica", flag: "🇩🇲" },
  { code: "+1", name: "República Dominicana", flag: "🇩🇴" },
  { code: "+593", name: "Ecuador", flag: "🇪🇨" },
  { code: "+20", name: "Egipto", flag: "🇪🇬" },
  { code: "+503", name: "El Salvador", flag: "🇸🇻" },
  { code: "+240", name: "Guinea Ecuatorial", flag: "🇬🇶" },
  { code: "+291", name: "Eritrea", flag: "🇪🇷" },
  { code: "+372", name: "Estonia", flag: "🇪🇪" },
  { code: "+268", name: "Esuatini", flag: "🇸🇿" },
  { code: "+251", name: "Etiopía", flag: "🇪🇹" },
  { code: "+679", name: "Fiyi", flag: "🇫🇯" },
  { code: "+358", name: "Finlandia", flag: "🇫🇮" },
  { code: "+33", name: "Francia", flag: "🇫🇷" },
  { code: "+241", name: "Gabón", flag: "🇬🇦" },
  { code: "+220", name: "Gambia", flag: "🇬🇲" },
  { code: "+995", name: "Georgia", flag: "🇬🇪" },
  { code: "+49", name: "Alemania", flag: "🇩🇪" },
  { code: "+233", name: "Ghana", flag: "🇬🇭" },
  { code: "+30", name: "Grecia", flag: "🇬🇷" },
  { code: "+1", name: "Granada", flag: "🇬🇩" },
  { code: "+502", name: "Guatemala", flag: "🇬🇹" },
  { code: "+224", name: "Guinea", flag: "🇬🇳" },
  { code: "+245", name: "Guinea-Bisáu", flag: "🇬🇼" },
  { code: "+592", name: "Guyana", flag: "🇬🇾" },
  { code: "+509", name: "Haití", flag: "🇭🇹" },
  { code: "+504", name: "Honduras", flag: "🇭🇳" },
  { code: "+36", name: "Hungría", flag: "🇭🇺" },
  { code: "+354", name: "Islandia", flag: "🇮🇸" },
  { code: "+91", name: "India", flag: "🇮🇳" },
  { code: "+62", name: "Indonesia", flag: "🇮🇩" },
  { code: "+98", name: "Irán", flag: "🇮🇷" },
  { code: "+964", name: "Irak", flag: "🇮🇶" },
  { code: "+353", name: "Irlanda", flag: "🇮🇪" },
  { code: "+972", name: "Israel", flag: "🇮🇱" },
  { code: "+39", name: "Italia", flag: "🇮🇹" },
  { code: "+1", name: "Jamaica", flag: "🇯🇲" },
  { code: "+81", name: "Japón", flag: "🇯🇵" },
  { code: "+962", name: "Jordania", flag: "🇯🇴" },
  { code: "+7", name: "Kazajistán", flag: "🇰🇿" },
  { code: "+254", name: "Kenia", flag: "🇰🇪" },
  { code: "+686", name: "Kiribati", flag: "🇰🇮" },
  { code: "+383", name: "Kosovo", flag: "🇽🇰" },
  { code: "+965", name: "Kuwait", flag: "🇰🇼" },
  { code: "+996", name: "Kirguistán", flag: "🇰🇬" },
  { code: "+856", name: "Laos", flag: "🇱🇦" },
  { code: "+371", name: "Letonia", flag: "🇱🇻" },
  { code: "+961", name: "Líbano", flag: "🇱🇧" },
  { code: "+266", name: "Lesoto", flag: "🇱🇸" },
  { code: "+231", name: "Liberia", flag: "🇱🇷" },
  { code: "+218", name: "Libia", flag: "🇱🇾" },
  { code: "+423", name: "Liechtenstein", flag: "🇱🇮" },
  { code: "+370", name: "Lituania", flag: "🇱🇹" },
  { code: "+352", name: "Luxemburgo", flag: "🇱🇺" },
  { code: "+261", name: "Madagascar", flag: "🇲🇬" },
  { code: "+265", name: "Malaui", flag: "🇲🇼" },
  { code: "+60", name: "Malasia", flag: "🇲🇾" },
  { code: "+960", name: "Maldivas", flag: "🇲🇻" },
  { code: "+223", name: "Malí", flag: "🇲🇱" },
  { code: "+356", name: "Malta", flag: "🇲🇹" },
  { code: "+692", name: "Islas Marshall", flag: "🇲🇭" },
  { code: "+222", name: "Mauritania", flag: "🇲🇷" },
  { code: "+230", name: "Mauricio", flag: "🇲🇺" },
  { code: "+52", name: "México", flag: "🇲🇽" },
  { code: "+691", name: "Micronesia", flag: "🇫🇲" },
  { code: "+373", name: "Moldavia", flag: "🇲🇩" },
  { code: "+377", name: "Mónaco", flag: "🇲🇨" },
  { code: "+976", name: "Mongolia", flag: "🇲🇳" },
  { code: "+382", name: "Montenegro", flag: "🇲🇪" },
  { code: "+212", name: "Marruecos", flag: "🇲🇦" },
  { code: "+258", name: "Mozambique", flag: "🇲🇿" },
  { code: "+95", name: "Birmania", flag: "🇲🇲" },
  { code: "+264", name: "Namibia", flag: "🇳🇦" },
  { code: "+674", name: "Nauru", flag: "🇳🇷" },
  { code: "+977", name: "Nepal", flag: "🇳🇵" },
  { code: "+31", name: "Países Bajos", flag: "🇳🇱" },
  { code: "+64", name: "Nueva Zelanda", flag: "🇳🇿" },
  { code: "+505", name: "Nicaragua", flag: "🇳🇮" },
  { code: "+227", name: "Níger", flag: "🇳🇪" },
  { code: "+234", name: "Nigeria", flag: "🇳🇬" },
  { code: "+47", name: "Noruega", flag: "🇳🇴" },
  { code: "+968", name: "Omán", flag: "🇴🇲" },
  { code: "+92", name: "Pakistán", flag: "🇵🇰" },
  { code: "+680", name: "Palaos", flag: "🇵🇼" },
  { code: "+970", name: "Palestina", flag: "🇵🇸" },
  { code: "+507", name: "Panamá", flag: "🇵🇦" },
  { code: "+675", name: "Papúa Nueva Guinea", flag: "🇵🇬" },
  { code: "+595", name: "Paraguay", flag: "🇵🇾" },
  { code: "+51", name: "Perú", flag: "🇵🇪" },
  { code: "+63", name: "Filipinas", flag: "🇵🇭" },
  { code: "+48", name: "Polonia", flag: "🇵🇱" },
  { code: "+351", name: "Portugal", flag: "🇵🇹" },
  { code: "+974", name: "Catar", flag: "🇶🇦" },
  { code: "+40", name: "Rumanía", flag: "🇷🇴" },
  { code: "+7", name: "Rusia", flag: "🇷🇺" },
  { code: "+250", name: "Ruanda", flag: "🇷🇼" },
  { code: "+1", name: "San Cristóbal y Nieves", flag: "🇰🇳" },
  { code: "+1", name: "Santa Lucía", flag: "🇱🇨" },
  { code: "+1", name: "San Vicente y las Granadinas", flag: "🇻🇨" },
  { code: "+685", name: "Samoa", flag: "🇼🇸" },
  { code: "+378", name: "San Marino", flag: "🇸🇲" },
  { code: "+239", name: "Santo Tomé y Príncipe", flag: "🇸🇹" },
  { code: "+966", name: "Arabia Saudita", flag: "🇸🇦" },
  { code: "+221", name: "Senegal", flag: "🇸🇳" },
  { code: "+381", name: "Serbia", flag: "🇷🇸" },
  { code: "+248", name: "Seychelles", flag: "🇸🇨" },
  { code: "+232", name: "Sierra Leona", flag: "🇸🇱" },
  { code: "+65", name: "Singapur", flag: "🇸🇬" },
  { code: "+421", name: "Eslovaquia", flag: "🇸🇰" },
  { code: "+386", name: "Eslovenia", flag: "🇸🇮" },
  { code: "+677", name: "Islas Salomón", flag: "🇸🇧" },
  { code: "+252", name: "Somalia", flag: "🇸🇴" },
  { code: "+27", name: "Sudáfrica", flag: "🇿🇦" },
  { code: "+82", name: "Corea del Sur", flag: "🇰🇷" },
  { code: "+211", name: "Sudán del Sur", flag: "🇸🇸" },
  { code: "+34", name: "España", flag: "🇪🇸" },
  { code: "+94", name: "Sri Lanka", flag: "🇱🇰" },
  { code: "+249", name: "Sudán", flag: "🇸🇩" },
  { code: "+597", name: "Surinam", flag: "🇸🇷" },
  { code: "+46", name: "Suecia", flag: "🇸🇪" },
  { code: "+41", name: "Suiza", flag: "🇨🇭" },
  { code: "+963", name: "Siria", flag: "🇸🇾" },
  { code: "+886", name: "Taiwán", flag: "🇹🇼" },
  { code: "+992", name: "Tayikistán", flag: "🇹🇯" },
  { code: "+255", name: "Tanzania", flag: "🇹🇿" },
  { code: "+66", name: "Tailandia", flag: "🇹🇭" },
  { code: "+228", name: "Togo", flag: "🇹🇬" },
  { code: "+676", name: "Tonga", flag: "🇹🇴" },
  { code: "+1", name: "Trinidad y Tobago", flag: "🇹🇹" },
  { code: "+216", name: "Túnez", flag: "🇹🇳" },
  { code: "+90", name: "Turquía", flag: "🇹🇷" },
  { code: "+993", name: "Turkmenistán", flag: "🇹🇲" },
  { code: "+688", name: "Tuvalu", flag: "🇹🇻" },
  { code: "+256", name: "Uganda", flag: "🇺🇬" },
  { code: "+380", name: "Ucrania", flag: "🇺🇦" },
  { code: "+971", name: "Emiratos Árabes Unidos", flag: "🇦🇪" },
  { code: "+44", name: "Reino Unido", flag: "🇬🇧" },
  { code: "+1", name: "Estados Unidos", flag: "🇺🇸" },
  { code: "+598", name: "Uruguay", flag: "🇺🇾" },
  { code: "+998", name: "Uzbekistán", flag: "🇺🇿" },
  { code: "+678", name: "Vanuatu", flag: "🇻🇺" },
  { code: "+58", name: "Venezuela", flag: "🇻🇪" },
  { code: "+84", name: "Vietnam", flag: "🇻🇳" },
  { code: "+967", name: "Yemen", flag: "🇾🇪" },
  { code: "+260", name: "Zambia", flag: "🇿🇲" },
  { code: "+263", name: "Zimbabue", flag: "🇿🇼" },
];
